### ISSUE TITLE
Linting never completes

### ISSUE THREAD

**Issue by robingram** [ikappas/vscode-phpcs#1]
When running on Windows 7. VS Code version 0.10.6.

phpcs is installed globally and in my path but even on a small file the status bar just sits saying 'phpcs is linting 1 document' with a spinner.

Is there any way I can get diagnostic output?

**Comment by glen-84** [comment]
I have the same issue. Windows 10. :disappointed:

**Comment by ikappas** [comment]
Hi and thank you for your feedback. There is no way to get diagnostic feedback but I will have a look at Windows 10 and get back to you

**Comment by glen-84** [comment]
@ikappas Did you find anything? Let me know if you need me to test something. =)

**Comment by shahnhogan** [comment]
+1

**Comment by krystianprzybyla** [comment]
+1

**Comment by Janne252** [comment]
+1

**Comment by Zarriff** [comment]
+1

**Comment by thanhngch** [comment]
+1 I have same issue in Windows 10.

**Comment by caffeinelogic** [comment]
+1

**Comment by meteor0763** [comment]
+1 - on OSX

**Comment by ChuckMac** [comment]
+1 - Win7

**Comment by temkretz** [comment]
+1 Win10

**Comment by ikappas** [comment]
I have just released 0.5.0 with updated dependencies for vscode 1.0.0

Can you please install and confirm whether this fixes your problem?

**Comment by glen-84** [comment]
@ikappas It's still not working. I also see the `This socket has been ended by the other party` error.

**Comment by ikappas** [comment]
@glen-84  Can you please confirm that you are also running phpmd and that this issue still occurs if you uninstall phpmd ?

**Comment by ikappas** [comment]
Also please open the output window and check what is going on there under phpcs

**Comment by glen-84** [comment]
@ikappas,

I'm not using phpmd. The output window shows:

`linting started on: file:///d%3A/Programming/Projects/x/website-front-end/config/container.php`

Could this be something to do with the encoding of the drive colon (`:`)?

**Comment by temkretz** [comment]
Sadly the update did fixed the problem only half, at least for me.

It no finishes but takes much time to finish.

Some info:

OS: MacOS X 10.11.4
PHPCS: PHP_CodeSniffer version 2.6.0 (stable) by Squiz (http://www.squiz.net)
VSCode: 1.0.0

**Comment by ikappas** [comment]
@glen-84  I can confirm this issue on Windows. I am trying to get a handle on it 
@temkretz I can confirm that phpcs 2.6.0 runs extremely slow... Can you please downgrade phpcs to a version <= 2.5 and let me know if this changes this behaviour?

**Comment by ArianeLu** [comment]
Same issue on phpcs 2.4, PHP 7.0.5 ,Windows 10:
"This socket has been ended by the other party: Error: This socket has been ended by the other party"

**Comment by ikappas** [comment]
I just published phpcs 0.6.0 which should take care of this issue.
Please let me know if this works!

**Comment by glen-84** [comment]
It works! :tada:

**Comment by ikappas** [comment]
Good to hear, closing this issue.

**Comment by AashikP** [comment]
I have this same issue with latest version of vscode and extension, running with phpcs 3.2.0.

Output:
`linting started on: file:///f%3A/xampp/htdocs/mysqli-class/includes/class-db.php
`

I do not believe its an issue with phpcs  since linting works fine on sublime and atom. 

**Current fix:** 
Downgrading phpcs to an older version (3.0.1) has fixed the issue for me.
